---
galaxy_info:
  author: WCC CCDC Team
  description: Automated scoring engine for CCDC practice
  company: Whatcom Community College
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - ccdc
    - security
    - scoring
    - competition

dependencies: []
