---
galaxy_info:
  author: WCC CCDC Team
  description: CCDC practice environment configuration
  company: Whatcom Community College
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Kali
      versions:
        - 2023
  galaxy_tags:
    - ccdc
    - security
    - linux

dependencies: []
